name: Go Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o whitelist.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: whitelist.exe
        path: whitelist.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: whitelist.exe

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: whitelist.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
