name: Go Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o whitelist.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: whitelist.exe
        path: whitelist.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Git tag
      id: tag
      run: |
        TAG_NAME=v1.0.${{ github.run_number }}
        git tag $TAG_NAME
        git push origin $TAG_NAME
        echo "::set-output name=TAG_NAME::$TAG_NAME"

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: whitelist.exe

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.TAG_NAME }}
        name: Release ${{ steps.tag.outputs.TAG_NAME }}
        body: "A new release"
        files: whitelist.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
