name: Build RDP Whitelist Tool

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 定义目标操作系统和架构
        goos: [windows, linux, darwin]
        goarch: [amd64, arm64]
        exclude:
          # 排除不常用的组合
          - goos: darwin
            goarch: arm64

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build Binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        # 设置输出文件名
        OUTPUT_NAME="rdp_whitelist_${{ matrix.goos }}_${{ matrix.goarch }}"
        if [ "${{ matrix.goos }}" == "windows" ]; then
          OUTPUT_NAME="${OUTPUT_NAME}.exe"
        fi
        
        # 编译
        go mod tidy
        go build -ldflags="-s -w" -o dist/$OUTPUT_NAME

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rdp-whitelist-${{ matrix.goos }}-${{ matrix.goarch }}
        path: dist/
        retention-days: 5

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          **/*.exe
          **/*rdp_whitelist_*
